### ISSUE TITLE
Dark mode is not enabled on startup

### ISSUE THREAD

**Issue by Loldogs** [krlvm/BeautySearch#3]
All other modifications from BeautySearch work on startup/Windows Explorer restart (except dark mode) it is only enabled when I right click a search option (showing the context menu).

**Comment by krlvm** [comment]
Fixed in [version 1.2.1](https://github.com/krlvm/BeautySearch/releases/tag/v1.2.1)

**Comment by Loldogs** [comment]
I have installed and then reinstalled (and uninstalled and reinstalled) the 1.2.1 update, but the issue is still there

**Comment by krlvm** [comment]
I can't reproduce it with v1.2.1, when I open Search and start type all is in dark. If you click in any free space on window it will become dark even if it's still be in light theme, and then it will be in dark until you change your system theme.

**Comment by krlvm** [comment]
![bs_work](https://user-images.githubusercontent.com/51774833/90988727-b820b980-e59d-11ea-8775-45e542a78e77.gif)

**Comment by krlvm** [comment]
Finally fixed in [version 1.4](https://github.com/krlvm/BeautySearch/releases/tag/v1.4)
